#!/usr/bin/python
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Library General Public License as published by
# the Free Software Foundation; version 2 only
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# Copyright 2004 Dag Wieers <dag@wieers.com>

from __future__ import generators
import os, sys, re, getopt, fcntl, termios, struct
import ConfigParser, urlparse, signal, resource

VERSION = "0.5"

enable = ('yes', 'on', 'true', '1')
disable = ('no', 'off', 'false', '0')

class Options:
	def __init__(self, args):
		self.count = -1
		self.sleep = 1
		self.disklist = None
		self.intlist = None
		self.netlist = None
		self.float = False

		try:
			opts, args = getopt.getopt (args, 'acdghilmnpsvyD:I:N:',
				['all', 'cpu', 'disk', 'help', 'int', 'load', 'mem', 'net',
				'page', 'proc', 'swap', 'sys', 'version', 'vm', 'vmstat',
				'float'])
		except getopt.error, exc:
			print 'dstat: %s, try dstat -h for a list of all the options' % str(exc)
			sys.exit(1)

		self.modlist = []

		for opt, arg in opts:
			if opt in ['-a', '--all']:
				self.modlist = [ 'cpu', 'disk', 'mem', 'net', 'page', 'sys' ]
			elif opt in ['-c', '--cpu']:
				self.modlist.append('cpu')
			elif opt in ['-h', '--help']:
				self.usage()
				self.help()
				sys.exit(0)
			elif opt in ['-d', '--disk']:
				self.modlist.append('disk')
			elif opt in ['-D']:
				self.disklist = arg.split(',')
			elif opt in ['-i', '--int']:
				self.modlist.append('int')
			elif opt in ['-g', '--page']:
				self.modlist.append('page')
			elif opt in ['-I']:
				self.intlist = arg.split(',')
			elif opt in ['-m', '--mem']:
				self.modlist.append('mem')
			elif opt in ['-l', '--load']:
				self.modlist.append('load')
			elif opt in ['-n', '--net']:
				self.modlist.append('net')
			elif opt in ['-N']:
				self.netlist = arg.split(',')
			elif opt in ['-p', '--proc']:
				self.modlist.append('proc')
			elif opt in ['-s', '--swap']:
				self.modlist.append('swap')
			elif opt in ['-y', '--sys']:
				self.modlist.append('sys')
			elif opt in ['-v', '--version']:
				self.version()
				sys.exit(0)
			elif opt in ['--vm', '--vmstat']:
				self.modlist = [ 'proc', 'mem', 'page', 'disk', 'sys', 'cpu' ]
				self.disklist = ('total',)
			elif opt in ['--float']:
				self.float = True

		if not self.modlist:
			self.modlist = [ 'cpu', 'disk', 'net', 'sys' ]

		if len(args) > 0:
			self.sleep = int(args[0])

		if len(args) > 1:
			self.count = int(args[1])

	def version(self):
		print 'Dstat %s' % VERSION
		print 'Written by Dag Wieers <dag@wieers.com>'
		print 'Homepage at http://dag.wieers.com/home-made/dstat/>'
		print
		print 'Platform %s/%s' % (os.name, sys.platform)
		print 'Python %s' % sys.version

	def usage(self):
		print 'usage: dstat [-acdgilmnpsy] [-D dev1..] [-I #..] [-N if1..] [delay [count]]'

	def help(self):
		print '''Versatile tool for generating system resource statistics

Dstat options:
  -a, --all          enable cpu, disk, mem, net, page and sys (eq. -cdmngy)
  -c, --cpu          enable cpu stats
  -d, --disk         enable disk stats
     -D total,hda       include hda and total
  -g, --page         enable page stats
  -i, --int          enable interrupt stats
     -I 5,eth2          include int5 and interrupt used by eth2
  -l, --load         enable load stats
  -m, --mem          enable memory stats
  -n, --net          enable network stats
     -N eth1,total      include eth1 and total
  -p, --proc         enable process stats
  -s, --swap         enable swap stats
  -y, --sys          enable system stats

  --float            show numbers as floats (more detail)
'''

class Config:
	def __init__(self):
		self.configfile = op.configfile
		self.cfg = ConfigParser.ConfigParser()

		(s,b,p,q,f,o) = urlparse.urlparse(self.configfile)
		if s in ('http', 'ftp', 'file'):
			configfh = urllib.urlopen(self.configfile)
			try:
				self.cfg.readfp(configfh)
			except ConfigParser.MissingSectionHeaderError, e:
				die(6, 'Error accessing URL: %s' % self.configfile)
		else:
			if os.access(self.configfile, os.R_OK):
				try:
					self.cfg.read(self.configfile)
				except:
					die(7, 'Syntax error reading file: %s' % self.configfile)
			else:
				die(6, 'Error accessing file: %s' % self.configfile)

	def getoption(self, section, option, var):
		"Get an option from a section from configfile"
		try:
			var = self.cfg.get(section, option)
			info(3, 'Setting option %s in section [%s] to: %s' % (option, section, var))
		except ConfigParser.NoSectionError, e:
			info(4, 'Failed to find section [%s] in %s' % (section, op.configfile))
		except ConfigParser.NoOptionError, e:
#			info(4, 'Failed to find option %s in [%s], set to default: %s' % (option, section, var))
			info(4, 'Setting option %s in section [%s] to: %s (default)' % (option, section, var))
		return var

class dstat:
	def init(self):
		if not self.check(): return

		self.title1 = self.set_title1()
		self.title2 = self.set_title2()

		### Initialise default variables
		self.val = {}
		self.cn1 = {}
		self.cn2 = {}
		for i in self.vars: self.val[i] = self.cn1[i] = self.cn2[i] = 0

	def set_title1(self):
		max = len(self.vars) * self.len + len(self.vars) - 1
		return self.name[0:max-2].center(max).replace(' ', '-')

	def set_title2(self):
		ret = ''
		for str in self.nick:
			ret = ret + str[0:self.len].center(self.len).replace(' ', '_')
			if str != self.nick[-1]: ret = ret + ' '
		return ret

	def check(self):
		return True

	def stats(self):
		pass

	def show(self):
		sep = ' '
		for name in self.vars:
			if self.format == '%s':
					sys.stdout.write(self.format % conv(self.len, self.val[name]))
			elif self.format in ('%s %s', '%s:%s', '%s-%s'):
					sys.stdout.write(self.format % convlist(self.len, self.val[name]))
					sep = ':'
			else:
					sys.stdout.write(self.format % self.val[name])
			if name != self.vars[-1]:
				sys.stdout.write(sep)

class dstat_cpu(dstat):
	def __init__(self):
		self.name = 'cpu usage'
		self.vars = ('user', 'sys', 'idle', 'wait')
		self.len = 3
		self.format = '%3d'
		self.nick = ( 'usr', 'sys', 'idl', 'wai' )
		self.init()
		self.cn1['sum'] = 0

	def check(self):
		if os.path.exists('/proc/stat'):
			return True
		return False

	def stats(self):
		for line in open('/proc/stat', 'r').readlines():
			l = line.split()
			if len(l) > 6 and l[0] == 'cpu':
				self.cn2['user'] = int(l[1]) + int(l[2])
				self.cn2['sys'] = int(l[3])
				self.cn2['idle'] = int(l[4])
				self.cn2['wait'] = int(l[5])
				self.cn2['sum'] = self.cn2['user'] + self.cn2['sys'] + self.cn2['idle'] + self.cn2['wait']
		for name in self.vars:
			self.val[name] = (100.0 * (self.cn2[name]-self.cn1[name]) + (self.cn2['sum']-self.cn1['sum']) / 2) / (self.cn2['sum']-self.cn1['sum'])
		self.cn1.update(self.cn2)

class dstat_disk(dstat):
	def __init__(self):
		if not self.check(): return
		self.format = '%s %s'
		self.len = 11
		self.name = 'disk i/o'
		self.uptime = 0 ### Needed for dstat_disk24
		if op.disklist:
			self.vars = op.disklist
		else:
			self.vars = self.discover()
		self.diskset = {
			'local': ('sda', 'hda', 'hdc'),
			'lores': ('sdb', 'sdc', 'sdd', 'sde', 'sdf', 'sdg', 'sdh', 'sdi', 'sdj', 'sdk', 'sdl', 'sdm', 'sdn', 'sdo', 'sdp', 'sdq', 'sdr', 'sds', 'sdt'),
			'hires': ('sdu', 'sdv', 'sdw', 'sdx', 'sdy', 'sdz', 'sdaa', 'sdab', 'sdac', 'sdad' ),
		}
		self.nick = self.vars
		self.init()

		for name in self.vars: self.cn1[name] = (0, 0)
		self.cn1['total'] = (0, 0)
		for name in self.vars: self.cn2[name] = (0, 0)
		self.cn2['total'] = (0, 0)
		for name in self.vars: self.val[name] = (0, 0)
		self.val['total'] = (0, 0)

	def discover(self):
		retlist = []
		for line in open('/proc/diskstats', 'r').readlines():
			dev = line.split()[2]
			if re.match('^(hd[a-z]|sd[a-z])$', dev):
				retlist.append(dev)
		if len(retlist) > 2: retlist = retlist[0:2]
		retlist.sort()
		return retlist

	def check(self):
		if os.path.exists('/proc/diskstats'):
			return True
		return False

	def stats(self):
		for name in self.vars: self.cn2[name] = (0, 0)
		for line in open('/proc/diskstats', 'r').readlines():
			l = line.split(); name = l[2]
			if name in self.vars:
#				print mountpoint('/dev/' + name)
#				bsize = os.statvfs(mountpoint('/dev/' + name))[0]
				self.cn2[name] = ( self.cn2[name][0] + int(l[5]), self.cn2[name][1] + int(l[9]) )
			for set in self.vars:
				if set in self.diskset and name in self.diskset[set]:
					self.cn2[set] = ( self.cn2[set][0] + int(l[5]), self.cn2[set][1] + int(l[9]) )
			if len(l) > 10:
				self.cn2['total'] = ( self.cn2['total'][0] + int(l[5]), self.cn2['total'][1] + int(l[9]) )
		if count != 0:
			for name in self.cn2:
				self.val[name] = ( 
					(self.cn2[name][0]-self.cn1[name][0]) * 512.0 / op.sleep,
					(self.cn2[name][1]-self.cn1[name][1]) * 512.0 / op.sleep,
				)
		self.cn1.update(self.cn2)

class dstat_disk24(dstat_disk):
	def discover(self):
		retlist = []
		for line in open('/proc/partitions', 'r').readlines():
			if len(line) < 4: continue
			dev = line.split()[3]
			if re.match('^(hd[a-z]|sd[a-z])$', dev):
				retlist.append(dev)
		if len(retlist) > 2: retlist = retlist[0:2]
		retlist.sort()
		return retlist
#		return ('local', 'lores', 'hires', 'total')

	def check(self):
		if os.path.exists('/proc/partitions') and os.uname()[2] < '2.4.22':
			return True
		return False

	def stats(self):
		for name in self.vars: self.cn2[name] = (0, 0)
		for line in open('/proc/stat', 'r').readlines():
			l = line.split()
			if len(l) > 7 and ( l[0] == 'cpu0' or l[0] == 'cpu' ):
				self.uptime2 = int(l[1]) + int(l[2]) + int(l[3]) + int(l[4]) + int(l[5]) + int(l[6]) + int(l[7])
#				self.uptime2 = sum(map(int, l[1-7]))

		itv = self.uptime2 - self.uptime

#		print '[up2=', self.uptime2, 'up=', self.uptime , ']',
#		print '[dup=', self.uptime2 - self.uptime , ']',
#		print '[itv=', itv, 'HZ=', hz , ']',

		self.uptime = self.uptime2

		for line in open('/proc/partitions', 'r').readlines():
			l = line.split();
			if len(l) < 10: continue
			name = l[3]
			if name == 'name': continue
			if name in self.vars:
				self.cn2[name] = ( self.cn2[name][0] + long(l[6]), self.cn2[name][1] + long(l[10]) )
			for set in self.vars:
				if set in self.diskset and name in self.diskset[set]:
					self.cn2[set] = ( self.cn2[set][0] + long(l[6]), self.cn2[set][1] + long(l[10]) )
			if len(l) > 10:
				self.cn2['total'] = ( self.cn2['total'][0] + long(l[6]), self.cn2['total'][1] + long(l[10]))
		if count != 0:
			for name in self.cn2:
				self.val[name] = ( 
					(self.cn2[name][0]-self.cn1[name][0]) * 1024.0 / itv * hz / 2.0,
					(self.cn2[name][1]-self.cn1[name][1]) * 1024.0 / itv * hz / 2.0,
				)
#		print '[rd=', self.cn2[name][0]-self.cn1[name][0], 'wr=', self.cn2[name][1]-self.cn1[name][1] , ']',
		self.cn1.update(self.cn2)

class dstat_disk24old(dstat_disk24):
	def check(self):
		if os.path.exists('/proc/stat') and os.uname()[2] < '2.4.22':
			return True
		return False

	def stats(self):
		for name in self.vars: self.cn2[name] = (0, 0)
		for line in open('/proc/stat', 'r').readlines():
			l = line.split(':'); name = l[0]
			if name == 'disk_io':
				for pair in line.split()[1:]:
					m = re.match('^\((\d+),(\d+)\):\(\d+,\d+,(\d+),\d+,(\d+)\)$', pair)
					if m:
						l = m.groups()
						name = dev(int(l[0]), int(l[1]))
						self.cn2[name] = ( int(l[2]), int(l[3]) )
						for set in self.vars:
							if set in self.diskset and name in self.diskset[set]:
								self.cn2[set] = ( self.cn2[set][0] + int(l[2]), self.cn2[set][1] + int(l[3]) )
						self.cn2['total'] = ( self.cn2['total'][0] + int(l[2]), self.cn2['total'][1] + int(l[3]) )
		if count != 0:
			for name in self.cn2:
				self.val[name] = (
					(self.cn2[name][0]-self.cn1[name][0]) * 512.0 / op.sleep,
					(self.cn2[name][1]-self.cn1[name][1]) * 512.0 / op.sleep,
				)
		self.cn1.update(self.cn2)

class dstat_int(dstat):
	def __init__(self):
		self.format = '%4d'
		self.len = 4
		self.name = 'interrupts'
		if op.intlist:
			self.vars = op.intlist
		else:
			self.vars = self.discover()
		self.nick = self.vars
		self.init()

	def discover(self):
		retlist = ()
		for line in open('/proc/interrupts', 'r').readlines():
			l = line.split(); name = l[0].split(':')[0]
			if name in ('0', '1', '2', '8', 'NMI', 'LOC', 'MIS', 'CPU0'):
				continue
			if len(l) > 1 and l[1] != '0':
				retlist = retlist + (name,)
		return retlist

	def check(self):
		if os.path.exists('/proc/interrupts'):
			return True
		return False

	def stats(self):
		for line in open('/proc/interrupts', 'r').readlines():
			l = line.split(); name = l[0].split(':')[0]
			if name in self.vars:
				self.cn2[name] = int(l[1])
			elif len(l) > 2 + procs:
				for hw in self.vars:
					for mod in l[2+procs:]:
						self.cn2[mod] = int(l[1])
		if count != 0:
			for name in self.cn2:
				self.val[name] = (self.cn2[name]-self.cn1[name]) * 1.0 / op.sleep
		self.cn1.update(self.cn2)

class dstat_load(dstat):
	def __init__(self):
		self.len = 4
		self.format = '%4.2f'
		self.name = 'load avg'
		self.nick = ('_1m', '_5m', '_15m')
		self.vars = ('load1', 'load5', 'load15')
		self.init()

	def check(self):
		if os.path.exists('/proc/loadavg'):
			return True
		return False

	def stats(self):
		for line in open('/proc/loadavg', 'r').readlines():
			l = line.split()
			self.val['load1'] = float(l[0])
			self.val['load5'] = float(l[1])
			self.val['load15'] = float(l[2])

class dstat_mem(dstat):
	def __init__(self):
		self.name = 'memory usage'
		self.len = 5
		self.format = '%s'
		self.nick = ('used', 'free', 'buff', 'cach')
		self.vars = ('MemUsed', 'MemFree', 'Buffers', 'Cached')
		self.init()

	def check(self):
		if os.path.exists('/proc/meminfo'):
			return True
		return False

	def stats(self):
		for line in open('/proc/meminfo', 'r').readlines():
			l = line.split()
			name = l[0].split(':')[0]
			if name in self.vars + ('MemTotal',):
				self.val[name] = int(l[1]) * 1024.0
		self.val['MemUsed'] = self.val['MemTotal'] - self.val['MemFree'] - self.val['Buffers'] - self.val['Cached']

class dstat_net(dstat):
	def __init__(self):
		self.name = 'network'
		self.len = 11
		self.format = '%s %s'
		if op.netlist:
			self.vars = op.netlist
		else:
			self.vars = self.discover()
		self.nick = self.vars
		self.init()

		for name in self.vars: self.cn1[name] = (0, 0)
		self.cn1['total'] = (0, 0)
		for name in self.vars: self.cn2[name] = (0, 0)
		self.cn2['total'] = (0, 0)
		for name in self.vars: self.val[name] = (0, 0)
		self.val['total'] = (0, 0)

	def discover(self):
		retlist = []
		for line in open('/proc/net/dev', 'r').readlines():
			iface = line.split()[0].split(':')[0]
			if re.match('^(bond\d|eth\d|wifi\d)$', iface):
				retlist.append(iface)
		if len(retlist) > 2: retlist = retlist[0:2]
		retlist.sort()
		return retlist

	def check(self):
		if os.path.exists('/proc/net/dev'):
			return True
		return False

	def stats(self):
		self.cn2['total'] = (0, 0)
		for line in open('/proc/net/dev', 'r').readlines():
			l = line.split()
			l2 = l[0].split(':')
			iface = l2[0]
			if len(l2) > 1 and l2[1].strip():
				l = l2[1:] + l[1:]
			else:
				l = l[1:]
			if iface in (self.vars) :
				self.cn2[iface] = ( long(l[0]), long(l[8]) )
			if re.match('^(bond\d|eth\d|wifi\d)$', iface):
				self.cn2['total'] = ( self.cn2['total'][0] + long(l[0]), self.cn2['total'][1] + long(l[8]))
		if count != 0:
			for name in self.cn2:
				self.val[name] = ( 
					(self.cn2[name][0]-self.cn1[name][0]) * 1.0 / op.sleep,
					(self.cn2[name][1]-self.cn1[name][1]) * 1.0 / op.sleep
				 )
		self.cn1.update(self.cn2)

class dstat_page(dstat):
	def __init__(self):
		self.name = 'paging'
		self.format = '%s'
		self.len = 5
		self.vars = ('pswpin', 'pswpout')
		self.nick = ('in', 'out')
		self.init()

	def check(self):
		if os.path.exists('/proc/vmstat'):
			return True
		return False

	def stats(self):
		for line in open('/proc/vmstat', 'r').readlines():
			l = line.split(); name = l[0]
			if name in self.vars:
				self.cn2[name] = int(l[1])
		if count != 0:
			for name in self.vars:
				self.val[name] = (self.cn2[name]-self.cn1[name]) * pagesize * 1.0 / op.sleep
		self.cn1.update(self.cn2)

class dstat_page24(dstat_page):
	def check(self):
		if os.path.exists('/proc/stat') and os.uname()[2] < '2.4.22':
			return True
		return False

	def stats(self):
		for line in open('/proc/stat', 'r').readlines():
			l = line.split(); name = l[0]
			if name == 'swap':
				self.cn2['pswpin'] = int(l[1])
				self.cn2['pswpout'] = int(l[2])
		if count != 0:
			for name in self.vars:
				self.val[name] = (self.cn2[name]-self.cn1[name]) * pagesize * 1.0 / op.sleep
		self.cn1.update(self.cn2)

class dstat_proc(dstat):
	def __init__(self):
#		self.name = 'procs'
		self.name = 'prc'
		self.format = '%2d'
		self.len = 2
#		self.vars = ('procs_running', 'procs_blocked', 'processes')
		self.vars = ('procs_running', 'procs_blocked')
#		self.nick = ('ru', 'bl', 'nw')
		self.nick = ('ru', 'bl')
		self.init()

	def check(self):
		if os.path.exists('/proc/stat'):
			return True
		return False

	def stats(self):
		for line in open('/proc/stat', 'r').readlines():
			l = line.split(); name = l[0]
			if name in self.vars:
				self.val[name] = int(l[1])
#			if name in ('processess',):
#				self.cn2[name] = int(l[1])
		self.val['procs_running'] = self.val['procs_running'] - 1
#		if count != 0:
#			self.val['processes'] = self.cn2['processes']-self.cn1['processes']
		self.cn1.update(self.cn2)

class dstat_swap(dstat):
	def __init__(self):
		self.name = 'swap'
		self.len = 5
		self.format = '%s'
		self.nick = ('used', 'free')
		self.vars = ('SwapUsed', 'SwapFree')
		self.init()

	def check(self):
		if os.path.exists('/proc/meminfo'):
			return True
		return False

	def stats(self):
		for line in open('/proc/meminfo', 'r').readlines():
			l = line.split()
			name = l[0].split(':')[0]
			if name in self.vars + ('SwapTotal',):
				self.val[name] = int(l[1]) * 1024.0
		self.val['SwapUsed'] = self.val['SwapTotal'] - self.val['SwapFree']

class dstat_sys(dstat):
	def __init__(self):
		self.name = 'system'
		self.format = '%5d'
		self.len = 5
		self.nick = ('int', 'csw')
		self.vars = ('intr', 'ctxt')
		self.names = { 'intr': 'int', 'ctxt': 'csw' }
		self.init()

	def check(self):
		if os.path.exists('/proc/stat'):
			return True
		return False

	def stats(self):
		for line in open('/proc/stat', 'r').readlines():
			l = line.split(); name = l[0]
			if l[0] in self.vars:
				self.cn2[l[0]] = int(l[1])
		if count != 0:
			for name in self.vars:
				self.val[name] = (self.cn2[name]-self.cn1[name]) * 1.0 / op.sleep
		self.cn1.update(self.cn2)

	def show(self):
		for name in self.vars:
			sys.stdout.write('%5d' % self.val[name])
			if name != self.vars[-1]:
				sys.stdout.write(' ')

def convlist(max, list):
	max = max / len(list)
	retlist = ()
	for var in list:
		retlist = retlist + (conv(max, var), )
	return retlist

#def convlist(max, list):
#	return map(conv, list)

def conv(max, var, base = 1024):
	### lowercase (b) is better for the eyes than uppercase
	units = ('B', 'k', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y')
	c = 0
	while True:
		if len('%d' % round(var)) < max:
			if op.float and len('%1.2f' % var) < max:
				ret = '%1.2f' % var
			elif op.float and len('%1.1f' % var) < max:
				ret = '%1.1f' % var
			else:
				ret = '%d' % round(var)
			break
		var = var / base
		c = c + 1
	if var != 0:
		return ret.rjust(max-1) + units[c]
	else:
		return ' ' * (max-2) + '0 '

def getwinsize():
	s = struct.pack("HHHH", 0, 0, 0, 0)
	try:
		x = fcntl.ioctl(sys.stdout.fileno(), termios.TIOCGWINSZ, s)
	except IOError:
		return (25, 80)
	return struct.unpack("HHHH", x)[:2]

def getcpunr():
	procs = 0
	for line in open('/proc/stat', 'r').readlines():
		name = line.split()[0]
		if len(name) == 4 and name[0:3] == 'cpu':
			procs = procs + 1
	return procs

def scsidev(nr):
	if nr < 26:
		return 'sd' + chr(ord('a') + nr)
	else:
		return 'sd' + chr(ord('a') -1 + nr/26) + chr(ord('a') + nr%26)

def dev(maj, min):
	scsi = [8, 65, 66, 67, 68, 69, 70, 71, 128, 129, 130, 131, 132, 133, 134, 135]
	ide = [3, 22, 33, 34, 56, 57, 88, 89, 90, 91]
	if maj in scsi:
		nr = scsi.index(maj) * 16 + min
#		nr = scsi.index(maj) * 16 + min / 16
		return scsidev(nr)
	elif maj in ide:
		nr = ide.index(maj) * 2 + min / 64
		return 'hd' + chr(ord('a') + nr)

#def mountpoint(dev):
#	"Return the mountpoint of a mounted device/file"
#	for entry in open('/etc/mtab', 'r').readlines():
#		if entry:
#			list = entry.split()
#			if dev == list[0]:
#				return list[1]

def handler(signum, frame):
	pass

def main():
	global count, pagesize, procs, hz
	count = 0
	pagesize = resource.getpagesize()
	procs = getcpunr()
	hz = os.sysconf('SC_CLK_TCK')

	olist = []
	for mod in op.modlist:
		if mod == 'cpu':	olist.append(dstat_cpu())
		elif mod == 'disk':
#			olist.append(dstat_disk24old())
			olist.append(dstat_disk24())
			olist.append(dstat_disk())
		elif mod == 'int':	olist.append(dstat_int())
		elif mod == 'load':	olist.append(dstat_load())
		elif mod == 'mem':	olist.append(dstat_mem())
		elif mod == 'net':	olist.append(dstat_net())
		elif mod == 'page':
			olist.append(dstat_page24())
			olist.append(dstat_page())
		elif mod == 'proc':	olist.append(dstat_proc())
		elif mod == 'swap':	olist.append(dstat_swap())
		elif mod == 'sys':	olist.append(dstat_sys())

	### Remove defect objects
	for o in olist + []:
		if not o.check():
			olist.remove(o)

	if os.geteuid() == 0:
		os.nice(-10)
#	sys.setcheckinterval(op.sleep * 1.5 * 100)
	signal.signal(signal.SIGALRM, handler)
	while count != op.count:
		signal.alarm(op.sleep)

		rows = getwinsize()[0]
		if count % (rows-2)  == 0:
			for o in olist:
				sys.stdout.write(o.title1)
				if o != olist[-1]: sys.stdout.write(' ')
			sys.stdout.write('\n')

			for o in olist:
				sys.stdout.write(o.title2)
				if o != olist[-1]: sys.stdout.write('|')
			sys.stdout.write('\n')

		for o in olist:
			o.stats()
			o.show()
			if o != olist[-1]: sys.stdout.write('|')
		sys.stdout.write('\n')

		count = count + 1

		if count != op.count:
			signal.pause()

### Workaround for python <= 2.2.1
try:
     True, False
except NameError:
     True = 1
     False = 0
Yes = yes = On = on = True
No = no = Off = off = False

### Workaround for python < 2.3
#def enumerate(sequence):
#    index = 0
#    for item in sequence:
#        yield index, item
#        index = index + 1

### Main entrance
if __name__ == '__main__':
	op=Options(sys.argv[1:])
#	cf=Config()
	try:
		main()
	except KeyboardInterrupt, e:
		print 'Exiting on user request'
		sys.exit(6)
	except OSError, e:
#		print e.errno
		print 'OSError: %s' %e
		sys.exit(7)

# vim:ts=4:sw=4
